version: '3.8'

services:
  redpanda:
    image: docker.redpanda.com/redpandadata/redpanda:v23.1.2
    container_name: redpanda
    ports:
      - "9092:9092"
    environment:
      - REDPANDA_ADVERTISED_KAFKA_API=redpanda:9092
    networks:
      - app-network

  generator:
    build: ./log-generator
    container_name: log-generator
    depends_on:
      - redpanda
    networks:
      - app-network

networks:
  app-network:
    driver: bridge